miky_resource:
    resources:
        miky_payment.payment:
            classes:
                model: %miky_payment.model.payment.class%
            contexts:
                admin: ~
        miky_payment.payment_method:
            classes:
                model: %miky_payment.model.payment_method.class%
            contexts:
                admin: ~
miky_grid:
    grids:
        miky_payment.admin.payment:
            resource: miky_payment.payment
            sorting:
                createdAt:
                    path: createdAt
                    direction: asc
            fields:
                email:
                    type: string
                    label: miky_user.email
                username:
                    type: string
                    label: miky_user.username
                enabled:
                    type: twig
                    label: miky_core.enabled
                    options:
                        template: MikyAdminBundle:Grid/Field:enabled.html.twig
            filters:
                email:
                    type: string
                    label: miky_user.email
                username:
                    type: string
                    label: miky_user.username
                enabled:
                    type: boolean
                    label: miky_core.enabled
            batch_actions:
                delete:
                    label: miky_core.delete
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete


        miky_payment.admin.payment_method:
            resource: miky_payment.payment_method
            sorting:
                createdAt:
                    path: createdAt
                    direction: asc
            fields:
                email:
                    type: string
                    label: miky_user.email
                username:
                    type: string
                    label: miky_user.username
                enabled:
                    type: twig
                    label: miky_core.enabled
                    options:
                        template: MikyAdminBundle:Grid/Field:enabled.html.twig
            filters:
                email:
                    type: string
                    label: miky_user.email
                username:
                    type: string
                    label: miky_user.username
                enabled:
                    type: boolean
                    label: miky_core.enabled
            batch_actions:
                delete:
                    label: miky_core.delete
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
